### ISSUE TITLE
Store arrays

### ISSUE THREAD

**Issue by mnapoli** [auraphp/Aura.Session#11]
Hi there,

Is the library supposed to work if I store arrays into the session?

Example:

``` php
$segment = $session->newSegment('Vendor\Package\ClassName');

$segment->foo = [
    'test'
];
```

Right now I'm not having luck with this, but I'm not sure I'm doing everything correctly. So is that supposed to work?

Thanks

**Comment by harikt** [comment]
Hey @mnapoli nice to see you here. Sure it should work with arrays.

I guess you may not be committing the data to get it saved.

https://github.com/auraphp/Aura.Session#session-security

Let me know if that helps!

**Comment by mnapoli** [comment]
Thanks! That's so stupid of me I read it but just forgot. I don't know how it was working in other parts of my app.

**Comment by harikt** [comment]
:+1:
