### ISSUE TITLE
update readme.txt, initialization failed

### ISSUE THREAD

**Issue by nicolae-stelian** [auraphp/Aura.Session#13]
The code that is in README (Getting Started) for init a session is not valid. 
$session = include "/path/to/Aura.Session/scripts/instance.php";

The file scripts/instance.php don't exists in  branch develop-2, exists only in branch develop.
In composer (https://packagist.org/packages/aura/session) the source  code is develop-2.

**Comment by harikt** [comment]
Hey @nicolae-stelian , 

Please use the v1 branch https://github.com/auraphp/Aura.Session/tree/develop  .

The one you mentioned is the upcoming v2 branch still on heavy development.

**Comment by nicolae-stelian** [comment]
Hey @harikt 
 At the end each version must have an updated documentation  :)
Thank'you :)

**Comment by harikt** [comment]
@nicolae-stelian yes it is a bit unknown to people which version they are reading I guess. 

I will try to address the same.  You are also welcome to improve things so others find it useful.

Thank you.
