### ISSUE TITLE
Flash values not on segments

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#19]
Hi Paul, 

I was recalling a message to the groups, flash messages will be removed on next load even if it is displayed or not .

That gives me a feeling of we probably don't need to call to get the segment to set the flash message.

**Comment by harikt** [comment]
May be flash messages can go in different place. So I am closing this. If you have a different thought you can re-open.

THanks

**Comment by harikt** [comment]
@pmjones as we can do `setFlash('message', "Something")` . `message` key itself seems to be a namespace.

So do we need to get a segment really ?

**Comment by pmjones** [comment]
The 'message' is a key within a segment (typically the segment is named for a fully qualified class). It needs to be in a segment so that Foo\Bar 'message' does not overwrite Baz\Dib 'message'.

**Comment by pmjones** [comment]
So, yes, it needs to be in a segment for deconfliction.

**Comment by harikt** [comment]
Really for flash we need segments ? I don't have a use case at-least for now :-) .

But I am not sure anyone have though.

**Comment by pmjones** [comment]
Yes, you need segments. Again, the idea is to make sure that a flash key 'foo' set by one library does not overwrite a flash key 'foo' set by a different library.

**Comment by harikt** [comment]
aah ok. I am seeing where your thoughts are.

Great! and thanks for clarifying it.
