### ISSUE TITLE
CsrfToken Constructor mis-using Segment accessor method

### ISSUE THREAD

**Issue by alc** [auraphp/Aura.Session#21]
Like the title says, when the [CsrfToken constructor is checking for an existing csrf token value](https://github.com/auraphp/Aura.Session/blob/develop-2/src/CsrfToken.php#L54), it's written as if Segment defines a __get method, but [Segment has a regular get() method instead](https://github.com/auraphp/Aura.Session/blob/develop-2/src/Segment.php#L91).

As a result, every time $session->getCsrfToken() is called, the token fails to find it's previous value from the session, and generates a new one...so no value can ever pass a $token->isValid() check.

**Comment by harikt** [comment]
Thank you @alc for reporting.

Plese see the patch, which will resolve the issue.

Thanks

**Comment by alc** [comment]
Thanks guys for the quick fix. I've really enjoyed using the v2 packages so far. Cheers for all your hard work!

**Comment by harikt** [comment]
You are welcome :+1:  and thanks for using aura. Please join google groups if you are not there https://groups.google.com/d/forum/auraphp .

Thank you
