### ISSUE TITLE
Flash never getting expired

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#23]
Once you set a flash, and retrive the flash, still the message not expiring ( v2 )

``` php
$segment = $session->getSegment('Cocoframework\Example\ContactResponder');
$segment->setFlashNow('message', 'Thank you!. Someone will shortly get in touch with you!');
echo$session->getSegment('Cocoframework\Example\ContactResponder')->getFlash('message');
```

**Comment by pmjones** [comment]
Setting the flash for "now" means it is available right now, _and_ in the next request. This is as opposed to setting a flash normally, where it is available _only_ in the next request and not right now. Does that makes sense?

**Comment by pmjones** [comment]
As a side note, this is a change from how flashes used to work in v1. Previously, they were "Read-Once". Now instead of disappearing when you read them, they only disappear after the next request, whether you read them or not. That behavior is more in line with the common expectations of flash messages.

**Comment by harikt** [comment]
> Setting the flash for "now" means it is available right now

agree 

> and in the next request

I don't like that concept.

Now is now. Next is next request I agree.

The problem is it never expires even when you load twice, thrice......

**Comment by pmjones** [comment]
"On the next request" is the point of a flash. ;-)

Now, if it _never_ goes away, that's a problem.

**Comment by harikt** [comment]
> "On the next request" is the point of a flash. ;-)

Yes I agree. If it is for next request then what is the purpose of now ;) .

Working with zf1 flash, and aura v1 flash I feel v2 will make more confusion for people if now is available in next request also.

Eg : I show some message . "Send" , and when the user load/ refresh he will see again the same one.

> Now, if it never goes away, that's a problem.

Yes this is the problem currently.

**Comment by pmjones** [comment]
@harikt try the newest version, merged from https://github.com/auraphp/Aura.Session/pull/24. I've been using the following script to try it out and it seems to work:

``` php
<?php
require '/Users/pmjones/Code/pmjones/Aura.Session/autoload.php';

$session_factory = new \Aura\Session\SessionFactory;
$session = $session_factory->newInstance($_COOKIE);

$segment = $session->getSegment('test');

$foo = isset($_GET['foo'])
    ? $_GET['foo']
    : null;

if ($foo) {
    $segment->setFlash('foo', $foo);
}

var_dump($segment->getFlash('foo'));

$session->commit();
?>
```

Note the `commit()` at the end; that seems to be needed.

**Comment by harikt** [comment]
@pmjones why not keep the commit in the session destruct ... So users don't need to call commit manually. Calling commit manually is a bit weird to me.

**Comment by harikt** [comment]
will test it, currently moved to v1 session.

**Comment by harikt** [comment]
Tested and it works without commit. I was using setFlashNow . Once again I will say if setFlashNow can be read now then there is no need to carry to next request. That is what setFlash does. 

I have no idea why people need flash now and on next request. Do you see any use case ?

**Comment by pmjones** [comment]
I can imagine that someone may want a value to be available _both_ now _and_ on the next request. But if you are very much opposed, I am OK with removing. If so, we should probably remove getFlashNext() as well.

**Comment by harikt** [comment]
> I can imagine that someone may want a value to be available both now and on the next request. 

If they need flash for now and next request let them set both. `setFlash()` and `setFlashNow()` 

>  But if you are very much opposed, I am OK with removing.

I don't find the need as I mentioned above. Let them set it twice if needed. Basically when I hear now, it is for now and not `now and next`. When I hear flash it is for next. ie why `setFlashNow` helps.

> If so, we should probably remove getFlashNext() as well

I don't know why you need to remove `getFlashNext` . 

Eg : Some people use in their view helper the call to `getFlashNext` with setting flash as `setFlash()` .

**Comment by pmjones** [comment]
If you only need a flash "now" then you don't need a flash. You can just set a property value somewhere. The only way "now" makes sense is if it is a flash for the next request, that you can _additionally_ read now.

**Comment by harikt** [comment]
may be your arguments are true. And I don't have trouble to close it. 

But I wonder whether it is the way we learned. So basically we break the old school learning :)

**Comment by pmjones** [comment]
> But I wonder whether it is the way we learned. So basically we break the old school learning :)

I don't understand what you're saying here.

**Comment by harikt** [comment]
I thought v1 of zf have flash now, and was trying to find it. Not getting it anyway. You can ignore it :) .

**Comment by harikt** [comment]
You are correct on this, some of them clears flash when it is read ( http://symfony.com/doc/current/components/http_foundation/sessions.html#session-data-management ) , some have method to clear the flash when we read the current flash message ( http://apigen.juzna.cz/doc/komola/ZendFramework/source-class-Zend_Controller_Action_Helper_FlashMessenger.html#177 ) .

Thank you.

**Comment by pmjones** [comment]
Very good sir; closing this, and feel free to reopen if needed.

**Comment by harikt** [comment]
@pmjones flash not getting currently.

I wonder why so :( .

See the responder  https://github.com/cocoframework/Cocoframework.Example/blob/30b05bb50161302f2902e82d92ffec94ad1634ce/src/Contact/Web/Responder/ContactResponder.php#L56-L61
