### ISSUE TITLE
Ability to set a TTL on a Segment

### ISSUE THREAD

**Issue by ecolinet** [auraphp/Aura.Session#26]
The idea is to be able to set different expiration time for each segment, that way it is possible to let expire the authentication information (for exemple), without losing the content of other Segments.

What do you think about that feature request ?

**Comment by harikt** [comment]
:+1:  PR always welcome .

**Comment by pmjones** [comment]
If you want to submit a PR I'll be happy to review, but I can imagine only problems with this. For example, how do we notify the user (or even track internally) that one segment has expired, but another has not? Etc., etc.
