### ISSUE TITLE
Why no hasFlash

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#27]
There is no hasFlash . Is it purposefully removed ?

**Comment by harikt** [comment]
@pmjones the flash is a bit buggy. It would be nice if you could have a look into this.

Thank!

**Comment by pmjones** [comment]
Flashes in v2 have changed from "read-once" to "propagate-once." As such there's not much need for a "hasFlash()" to peek at it without actually reading it, since the flash values are already set.
