### ISSUE TITLE
Add remember me functionality

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#28]
Hi Paul, 

I feel session should have the remember me functionality than the Auth. 

It seems to me the functionality of session to save the cookie.

What do you think ?

**Comment by harikt** [comment]
I noticed this is already possible. Will send an update on docs.

Thanks

**Comment by harikt** [comment]
If anyone is looking for the same 

``` php
<?php
$session_factory = new \Aura\Session\SessionFactory;
$session = $session_factory->newInstance($_COOKIE);
$session->setCookieParams(array('lifetime' => '3600'));
```

**Comment by harikt** [comment]
@pmjones I am sad that a few issues opened and a few PR's like this are not merged before the beta-2 release :-( .

**Comment by pmjones** [comment]
Sorry dude -- I failed to check the issues before releasing. I will add a reminder in the release script.
