### ISSUE TITLE
Difference between versions and branches

### ISSUE THREAD

**Issue by CMCDragonkai** [auraphp/Aura.Session#3]
Hello.

I noticed that develop and master branch differ by their composer. But the tagged version 1.0 is even more different?

Which one is more stable and more awesome to use?

**Comment by harikt** [comment]
Hi @CMCDragonkai ,

Master is the current stable release . All the development will be in develop branch . Once we fix or create new features and feels it safe to release the develop will be merged to master and tagged .

So the current tagged version is 1.0.0 which is stable release and the current master is 1.0.0 . 

When 1.1.0 or 1.0.1 is released the master will be that . Hope that helps.
