### ISSUE TITLE
Cookie encryption / decryption

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#30]
Hi Paul, 

I am wondering what will be the best way to encrypt the data of cookies. Do you have any idea ?

I know a few frameworks ( Slim ) that do encryption with mcrypt .

**Comment by harikt** [comment]
I am looking at @enygma 's implementation https://github.com/psecio/session-encrypt , but I doubt how it behaves, when people move the session handler to make use of redis, mongo or db based handlers .

**Comment by enygma** [comment]
Yeah, the encryption there is sound but that handler only supports file-based sessions. It never was made for other storage mechanisms. I can't imagine it'd be overly difficult to add though.

**Comment by harikt** [comment]
Thank you @enygma . May be add some handlers for it then ? I can open a ticket there.

**Comment by enygma** [comment]
sure, wouldn't be too hard to pass into the `init` with some kind of standardized interface.

**Comment by harikt** [comment]
Closing in favour of https://github.com/psecio/session-encrypt/issues/5
