### ISSUE TITLE
Session commit method

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Session#31]
Hi Paul, 

In v2 I have not used commit but the session is still available. Does that mean we need to modify the docs https://github.com/auraphp/Aura.Session#saving-clearing-and-destroying-sessions

**Comment by pmjones** [comment]
Not sure what you're asking here. Can you give an example?

**Comment by harikt** [comment]
@pmjones sorry that I missed to get the notification.

What I was saying was even though I was not committing the session data was available. And do you still see the value of commit method when the session data is available on subsequent requests.

And I am not having the code for now. I don't know where I was experimenting this months back.

**Comment by pmjones** [comment]
Ah, so you're saying that calling `commit()` explicitly is not a strict requirement. I can note something like that in the README.

**Comment by harikt** [comment]
yes it was like that when I tried.
