### ISSUE TITLE
Can you please tell me what kind of encryption do you use to store data?

### ISSUE THREAD

**Issue by hatrena** [auraphp/Aura.Session#56]

**Comment by harikt** [comment]
Hi @hatrena , 

Thank you for your interest in encryption. Aura.Session currently don't use anything, but you are not limited to create / use one.

Eg : You can use https://github.com/psecio/session-encrypt with Aura.Session .

Let me know if you have any difficulties regarding the same.

**Comment by harikt** [comment]
Forgot to mention there is another package also : https://github.com/ezimuel/PHP-Secure-Session . You may find more packages . So feel free to use anyone with Aura.Session. 

If you are fine, we can close the issue.

Thank you

**Comment by hatrena** [comment]
@harikt Thanks for the suggestions

**Comment by harikt** [comment]
You are welcome. 

I hope we can close the issue in case we don't hear any other complaints.

Thank you
