### ISSUE TITLE
Cookie Params

### ISSUE THREAD

**Issue by stefanvonfintel** [auraphp/Aura.Session#58]
Hi.

Can you anyone explain why my cookie parameters are being reset whenever I do a redirect or navigate to a new page? Apologies if I am doing something wrong here. So I start with the following:

**index.php**

```
require_once("autoload.php");

$session_factory = new \Aura\Session\SessionFactory;
$session = $session_factory->newInstance($_COOKIE);
$session->setCookieParams(array('lifetime' => '10','httponly' => true));
$segment = $session->getSegment('Vendor\Package\ClassName');
$segment->set('username', 'new person');
$segment->set('usertype', 'enduser');

header('Location: welcome.php');
exit(0);
```

When I var_dump $session on index.php I get the following for the cookie params:

```
...
["cookie_params":protected]=>
  array(5) {
    ["lifetime"]=>
    string(2) "10"
    ["path"]=>
    string(1) "/"
    ["domain"]=>
    string(0) ""
    ["secure"]=>
    bool(false)
    ["httponly"]=>
    bool(true)
  }
...
```

**welcome.php**

```
require_once("autoload.php");

$session_factory = new \Aura\Session\SessionFactory;
$session = $session_factory->newInstance($_COOKIE);
$segment = $session->getSegment('Vendor\Package\ClassName');
```

When I var_dump $session on welcome.php I get the following for the cookie params:

```
....
["cookie_params":protected]=>
  array(5) {
    ["lifetime"]=>
    int(0)
    ["path"]=>
    string(1) "/"
    ["domain"]=>
    string(0) ""
    ["secure"]=>
    bool(false)
    ["httponly"]=>
    bool(false)
  }
....
```

Any insight on this?
Thanks

**Comment by stefanvonfintel** [comment]
Can I please get a response to this?

**Comment by pmjones** [comment]
That method uses [session_set_cookie_params](http://php.net/manual/en/function.session-set-cookie-params.php) under the hood. "The effect of this function only lasts for the duration of the script. Thus, you need to call session_set_cookie_params() for every request and before session_start() is called." So, for session cookie params to be "permanent" you need to set them in php.ini, or else set them in a bootstrap script that runs on every page load.

Does that help?

**Comment by stefanvonfintel** [comment]
Thanks alot!

That did help.

**Comment by pmjones** [comment]
Excellent. :-)
