### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by quevlu** [auraphp/Aura.Session#60]
Hi,

I am using Aura and i have a many questions :

1- Can i set the entriopy of cookie value ?
2 - Can i set the method of hashing value?
3- Can i get a instance of session to check if exists?
4- When i get the csrf token, it generates a new token and new session but it doesn't have a first token generated

**Comment by harikt** [comment]
> 1- Can i set the entriopy of cookie value ?

There is no entropy concept for cookie value in the library.

> 2 - Can i set the method of hashing value?

There is no hashing method built in. You can use your own.

> 3- Can i get a instance of session to check if exists?

There is no method to check if session exists or not. Only get value is provided. So you can check if it is empty / null.

> 4- When i get the csrf token, it generates a new token and new session but it doesn't have a first token generated

Not sure about this. The tests seems not having such an issue.

Sorry for the late reply. I am closing this for now.
