### ISSUE TITLE
Can not set the session_name or session_params with PHP 7.2

### ISSUE THREAD

**Issue by timeceeper** [auraphp/Aura.Session#65]
i can not set the session_name or session_param.

'session_set_cookie_params(): Cannot change session cookie parameters when session is active' in '\library\Aura\Session\Phpfunc.php' line 33

I think the session_set_cookie_params have to be called bevor creating the instance?

I have seen, that the project is not updated since 2 years. Is there another library uptodate?

with regards 
Andy

**Comment by waynehaffenden** [comment]
Any update on this, I have the same problem?

**Comment by robbertrosario** [comment]
Has this ever been fixed? I am also running into this problem with v2...

**Comment by harikt** [comment]
Hi there, 

Apologies for the delay in writing back. This is also similar to #70 and @koriym and @NaokiTsuchiya has commented on those. https://github.com/auraphp/Aura.Session/issues/70#issuecomment-1717437756 

So this seems not a problem with aura itself. But we can improve the documentation a bit.
