### ISSUE TITLE
getFlash doesn't fetch flash session data set via setFlash in previous request

### ISSUE THREAD

**Issue by swport** [auraphp/Aura.Session#69]
`Segment.php`
Perhaps, I asked the wrong question. But when I set some data with `setFlash` on a request which, supposedly, meant to be utilised in the next request (only), I receive a `NULL` on `getFlash` call - which shouldn't be the case.

Is it only meant to be utilised in the similar request?

PS: Please check my pull request regarding the same. I'm using this library with `Slim - microframework for PHP`

Thank you

**Comment by harikt** [comment]
Hey,
I have used the same functionality and have not experienced any trouble. https://github.com/auraphp/Aura.Session/pull/68/files .

Did you make sure you are redirecting / using the same segments etc ?

**Comment by harikt** [comment]
By the way I am using it inside expressive 

https://github.com/harikt/web.expressive/blob/3ff915dc023360abab3d0fb7ee910095bd295158/src/Http/Middleware/VerifyCsrfToken.php#L39-L40

https://github.com/harikt/web.expressive/blob/3ff915dc023360abab3d0fb7ee910095bd295158/src/Http/Handler/Auth/LoginHandler.php#L130-L131

Let me know if that helps or not.

**Comment by harikt** [comment]
You could also use these methods `setFlashNow($key, $val)` 

`getFlashNext($key, $alt)` : To read a value that will be available in the next request.

I wonder whether the request have been redirected again to see the flash. Show some code, so can debug the same.
