### ISSUE TITLE
Flash messages not working in MVC layout?

### ISSUE THREAD

**Issue by zkwbbr** [auraphp/Aura.Session#71]
I can get the flash messages working fine on plain PHP pages but when I try to use it in an MVC style setup, it doesn't work anymore. The `set()` and `get()` _Session_ methods work fine though.

I thought maybe my MVC layout is the problem but I tried other flash message packages such as `slim/flash` and it works fine.

Anybody else having issues with flash messages?

Btw, the README doc doesn't seem to be updated, it says:

> We can do so on a per-segment basis by calling the Segment keepFlash() method, or we can keep all flashes for all segments by calling the _Session_ `keepFlash()` method.

But there's seem to be no `keepFlash()` method in the _Session_ object

**Comment by harikt** [comment]
keepFlash method is inside the segment https://github.com/auraphp/Aura.Session/blob/3da5e9902bebcdae188aca0c9facb4d0976d0017/src/Segment.php#L207 . 

You are correct Inside the session object there is no `keepFlash` or `clearAll`

**Comment by harikt** [comment]
Documentation is fixed. Regarding the flash not sure why it is not working at your end as we have limited information of your code. So closing this for now.
