### ISSUE TITLE
aura session segment error

### ISSUE THREAD

**Issue by enes-testig** [auraphp/Aura.Session#74]
https://prnt.sc/17mxepl

I can't find the reason why I am getting an error on this line while coding in my project. whereas my software engineer did the same thing and worked on it, but it didn't work for me and I couldn't find a solution what exactly he meant here, what is the error, how can I fix it?

**Comment by koriym** [comment]
Perhaps you are running on PHP 7.3 or lower?
In any case, the syntax error has nothing to do with this library and we will close this issue.
