### ISSUE TITLE
4.x branch

### ISSUE THREAD

**Issue by koriym** [auraphp/Aura.Session#76]
@harikt @pmjones 

I've created a PR based on 3.x that supports PHP 7.2 to 8.1. #75 

I would like to create branch 4.x, however, there are still PRs that have not been merged. What should I do? Do we merge them and then create 4.x?

**Comment by harikt** [comment]
Hi,
If merging those pr are simple. You can proceed and merge to 4.x as well.If not we may want to go with 4.x.

**Comment by koriym** [comment]
Got it!

**Comment by koriym** [comment]
@harikt I have created a 4.x branch and #75  is ready for review.

**Comment by koriym** [comment]
Also I change the default branch to 4.x.
