### ISSUE TITLE
unit tests failing?

### ISSUE THREAD

**Issue by mindplay-dk** [auraphp/Aura.Session#8]
Both `develop-2` and `master` is showing 16 errors with phpunit run under the console under either PHP 5.3 or 5.4, are you aware of this issue?

```
There were 16 errors:

1) Aura\Session\CsrfTokenTest::testLaziness

session_start(): Cannot send session cookie - headers already sent by (output started at C:\workspace\test\Aura.Session\tests\phpunit.phar:2)

... (more like this) ...

FAILURES!
Tests: 32, Assertions: 34, Errors: 16.
```

I'm not even sure how headers could be "sent" when it's running under a console?

Perhaps the phpunit configuration needs to be configured to suppress the message or output (or whatever) if that's what causing output to start - or maybe you need to wrap the test suite in `ob_start()` and `ob_get_clean()` to avoid output starting or something?

**Comment by mindplay-dk** [comment]
How mature is `develop-2`? Do you recommend using it or staying away for now?

**Comment by harikt** [comment]
@mindplay-dk I was having a similar issue. Not sure on which repo I opened, and it was only happening in my `phpunit.phar` used a global composer installation.

**Comment by harikt** [comment]
Regarding `develop-2` I don't know .

**Comment by mindplay-dk** [comment]
Adding these lines to `SessionTest::setUp()` reduced number of errors from 16 to 9 on my system:

```
ini_set('session.use_cookies', 0);
ini_set('session.cache_limiter', '');
```

**Comment by mindplay-dk** [comment]
Aha, solved it!

Add the above two lines to the end of `bootstrap.php` instead of in `SessionTest` - these lines need to execute before PHPUnit has a chance to output it's status message.

All tests showing green under PHP 5.3 and 5.4 on my system now!
