### ISSUE TITLE
Latest stable release?

### ISSUE THREAD

**Issue by gRegorLove** [auraphp/Aura.Session#88]
I have been using the latest release via Composer (2.1.0) in some projects pretty smoothly (thanks!), but I noticed there are newer branches 3.x and 4.x here. What is the latest stable branch and will there be a new Composer release for it? Presuming those branches are stable, is there documentation for migrating from 2.x?

(Originally published at: https://gregorlove.com/2023/01/latest-stable-release/)

**Comment by harikt** [comment]
Hi there,

3.x can be ignored. Lets concentrate on 4.x and why it is not released.

There is another component Aura.Auth where session interface need to be used. You can see https://github.com/auraphp/Aura.Session/issues/86 .

That means we need to make sure nothing breaks in the new interface, so both Aura.Session and Aura.Auth can work smoothly. I was not getting enough time to concentrate into the project. That is why the 4.x of this repo is not released. But you can still continue to use 2.x branch without any trouble I guess.

**Comment by harikt** [comment]
Separation of interfaces seems not possible for the current time. So we may release a 4.x for those who need to use in higher php versions.
