### ISSUE TITLE
Access Session from Different Domains

### ISSUE THREAD

**Issue by RichPitul** [auraphp/Aura.Session#89]
I thought this would be simple but I can't seem to figure out exactly how to make this work. 

I have created a simple api which stores a user's email in an Aura Session on one domain.  Let's call that domain login.domain.com
On multiple other sites I am trying to make a POST to that domain to retrieve the user's email that is logged in but because they are all different domains making the call; I need to somehow resume the session that is started on login.domain.com.

I tried to pass the session id into the session in various ways but it doesn't seem to work. Is there a way to pass a known session id into Aura to reconnect to an active session? Given that I have the session id I think it should be possible to do I just can't seem to find the correct function to call; or the correct order to call it in.

**Comment by koriym** [comment]
Sharing session keys between different domains is a security risk and is generally discouraged. Aura.Session is a very simple library and I don't think there is any functionality to assist with such a thing.
